### ISSUE TITLE
Overall.Perspective

### ISSUE THREAD

**Issue by petereast** [ce201-group11/docs#12]

**Comment by obedsandow** [comment]
[SRS Product Perspective.docx](https://github.com/ce201-group11/docs/files/1505774/SRS.Product.Perspective.docx)

**Comment by petereast** [comment]
A couple of small things:

Under main features:
- Mention the data intake as a main feature
- Talk about the configurability of the graphs.

**Comment by obedsandow** [comment]
[SRS.Product.Perspective.docx](https://github.com/ce201-group11/docs/files/1517916/SRS.Product.Perspective.docx)
