### ISSUE TITLE
Overall.Functions

### ISSUE THREAD

**Issue by petereast** [ce201-group11/docs#13]

**Comment by petereast** [comment]
One thing:
- Please could you talk briefly about the aggregations of data in the lines. (eg sum and average of one or more series of data)

**Comment by petereast** [comment]
Oh yeah, and please clarify that in the output file, each graph from each tab will be exported into a single pdf.

**Comment by chrishylandcid** [comment]
[2.2 Product Functions (V2).docx](https://github.com/ce201-group11/docs/files/1515612/2.2.Product.Functions.V2.docx)

**Comment by petereast** [comment]
Please could you put this in the compiled document :)

**Comment by chrishylandcid** [comment]
Done.
