### ISSUE TITLE
Overall.User Characteristics

### ISSUE THREAD

**Issue by petereast** [ce201-group11/docs#14]

**Comment by Batman347** [comment]
[User Characteristics.docx](https://github.com/ce201-group11/docs/files/1507725/User.Characteristics.docx)

**Comment by petereast** [comment]
It's good, although it might be necessary to go into a little bit more detail about the user's experiences with user interfaces - for example "all the users of this software will have experience using Microsoft Windows, and Microsoft Office, so our software should follow similar design decisions" or something like that.

**Comment by Batman347** [comment]
[User Characteristics.docx](https://github.com/ce201-group11/docs/files/1515034/User.Characteristics.docx)
