### ISSUE TITLE
Overall.Constraints

### ISSUE THREAD

**Issue by petereast** [ce201-group11/docs#15]

**Comment by Batman347** [comment]
[Constraints.docx](https://github.com/ce201-group11/docs/files/1507722/Constraints.docx)

**Comment by petereast** [comment]
Another couple of constraints to think about: 
- We're dealing with a potentially large dataset (especially with Java overheads) so the system needs to handle that without overusing processing/memory resources.
- We also need to think about the OS environment that we're going to be operating in - the user won't have any administrative access (and so won't be able to install any 3rd party software like DBMS etc)

**Comment by petereast** [comment]
Those comments weren't intended to be copied and pasted across. Please could you write them in your own words :) @Batman347

**Comment by Batman347** [comment]
[Constraints.docx](https://github.com/ce201-group11/docs/files/1514922/Constraints.docx)
Sorry about that, a bit lazy there :)

**Comment by petereast** [comment]
Much better, thanks :) 👍
