### ISSUE TITLE
SRS.Proofread

### ISSUE THREAD

**Issue by petereast** [ce201-group11/docs#23]

**Comment by petereast** [comment]
Any remarks from the proofread?

**Comment by chrishylandcid** [comment]
Haven't had a proper proofread just yet. When I was looking for definitions, I spotted some grammar mistakes and fixed them, but that was all.

**Comment by petereast** [comment]
Thanks - much appreciated 👍

**Comment by petereast** [comment]
I've had a quick read through, but at this point my mind is basically mush so I've approved it.
