### ISSUE TITLE
Introduction.Scope

### ISSUE THREAD

**Issue by petereast** [ce201-group11/docs#9]

**Comment by petereast** [comment]
@chrishylandcid How's this going?

**Comment by chrishylandcid** [comment]
Still working on it. Will be done by the time we meet up today.

**Comment by petereast** [comment]
Excellent, thanks 👍

**Comment by chrishylandcid** [comment]
[Scope.docx](https://github.com/ce201-group11/docs/files/1517743/Scope.docx)
Peter, could you take a quick look at this to check if everything's alright?

**Comment by petereast** [comment]
All good - could you add it to the main document pls 👍 :)

**Comment by chrishylandcid** [comment]
Done.
